upgrade

diff --git a/nikite-deploy/Dockerfile b/nikite-deploy/Dockerfile
--- a/nikite-deploy/Dockerfile
+++ b/nikite-deploy/Dockerfile
@@ -1,27 +1,57 @@
-ARG NODE_VERSION=22
+ARG NODE_VERSION=22-alpine
 
-FROM node:${NODE_VERSION}-alpine AS builder
+FROM node:${NODE_VERSION} AS base
 
-WORKDIR /
 
-COPY nginx.conf /           
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-COPY package.json yarn.lock ./
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-RUN yarn install --frozen-lockfile
 
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
 RUN yarn build
 
-FROM nginx:alpine
-
-COPY --from=builder ./.next/ /usr/share/nginx/html
-COPY --from=builder /nginx.conf /etc/nginx/conf.d/default.conf
+FROM base AS runner
+WORKDIR /app
 
 ENV NODE_ENV production
-ENV PORT 3000
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
 
 EXPOSE 3000
 
-CMD ["nginx", "-g", "daemon off;"]
+ENV PORT 3000
+# set hostname to localhost
+ENV HOSTNAME "0.0.0.0"
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+CMD ["node", "server.js"]
+
